In [5]:
!pip install git+https://github.com/maxtuno/peqnp-lib

  Cloning https://github.com/maxtuno/peqnp-lib to /private/var/folders/ft/__54xk3s3kldbg7ch3wbqfq40000gn/T/pip-req-build-89xxn3wj
  Running command git clone -q https://github.com/maxtuno/peqnp-lib /private/var/folders/ft/__54xk3s3kldbg7ch3wbqfq40000gn/T/pip-req-build-89xxn3wj
  Created wheel for PEQNP: filename=PEQNP-0.0.1-cp37-none-any.whl size=4828173 sha256=c1fe9962562a93fec161efedc97fec2f9878c717e3df74ab7cf5df9c412c2eef
  Stored in directory: /private/var/folders/ft/__54xk3s3kldbg7ch3wbqfq40000gn/T/pip-ephem-wheel-cache-3r_ydsu4/wheels/1e/da/35/e31ad652fdc2862ac59c316f1c03b17f204de12a9bf8ff8051
Successfully built PEQNP


In [6]:
import peqnp

# Boolean Variables

In [7]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
assert x <= 1
while tc.satisfy([x]):
    print(x)

0
1


# Two Boolean Variables

In [8]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
assert x <= 1
assert y <= 1
while tc.satisfy([x, y]):
    print(x, y)

0 0
0 1
1 0
1 1


# Boolean Variables Relations (AND, OR, XOR)

In [8]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
assert x <= 1
assert y <= 1
assert x & y == 1
while tc.satisfy([x, y]):
    print(x, y)

1 1


In [9]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
assert x <= 1
assert y <= 1
assert x | y == 1
while tc.satisfy([x, y]):
    print(x, y)

1 0
0 1
1 1


In [10]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
assert x <= 1
assert y <= 1
assert x ^ y == 1
while tc.satisfy([x, y]):
    print(x, y)

1 0
0 1


# Integer Variable 4 bits

In [11]:
tc = peqnp.TheCore(bits=4, key='tutorial', folder='db/')
x = tc.int()
while tc.satisfy([x]):
    print(x)

0
4
1
2
3
5
6
7
8
12
9
13
10
11
14


# Three Integer Variable 6 bits

In [19]:
tc = peqnp.TheCore(bits=5, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
assert x + y == z
while tc.satisfy([x, y, z]):
    print(x, y, z)

0 1 1
0 17 17
16 1 17
1 0 1
1 16 17
17 0 17
0 16 16
16 0 16
0 0 0
8 9 17
9 8 17
8 8 16
2 1 3
18 1 19
2 17 19
3 0 3
2 0 2
19 0 19
3 16 19
18 0 18
2 16 18
4 1 5
20 1 21
4 17 21
5 0 5
4 0 4
21 0 21
5 16 21
20 0 20
4 16 20
24 1 25
8 17 25
9 16 25
8 16 24
25 0 25
24 0 24
9 0 9
8 1 9
8 0 8
17 4 21
1 18 19
17 8 25
1 24 25
1 2 3
17 2 19
1 20 21
16 9 25
1 4 5
16 5 21
0 3 3
0 19 19
16 3 19
0 18 18
16 2 18
0 2 2
1 8 9
0 21 21
0 25 25
0 5 5
0 20 20
16 4 20
0 4 4
0 9 9
0 24 24
16 8 24
0 8 8
17 1 18
2 19 21
18 3 21
2 3 5
1 17 18
1 1 2
3 18 21
19 2 21
3 2 5
2 18 20
18 2 20
2 2 4
4 21 25
5 12 17
2 5 7
0 7 7
2 4 6
0 6 6
6 0 6
4 2 6
6 1 7
4 3 7
12 0 12
12 1 13
8 4 12
8 5 13
0 12 12
0 13 13
4 8 12
4 9 13
2 9 11
0 11 11
2 8 10
0 10 10
10 0 10
8 2 10
10 1 11
8 3 11
14 1 15
12 3 15
6 9 15
4 10 14
12 2 14
14 0 14
8 7 15
10 5 15
10 4 14
8 6 14
0 14 14
0 15 15
4 11 15
2 12 14
2 13 15
6 8 14
22 8 30
18 8 26
18 12 30
16 12 28
16 14 30
20 10 30
20 8 28
16 10 26
28 0 28
24 4 28
24 2 26
26 0 26
28 2 30
24 6 30
26 4

# Three Integer Variable 4 bits Operations

In [26]:
tc = peqnp.TheCore(bits=4, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
assert x ** 2 + y ** 3 == x * y - z
while tc.satisfy([x, y, z]):
    print(x, y, z)

2 1 13
2 0 12
2 2 8
1 2 9
0 0 0
3 0 7
3 1 9
0 2 8


# Three Integer Variable 10 bits Exponential Variables

In [32]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
assert x ** y == z
assert x > 1
assert y > 1
while tc.satisfy([x, y, z]):
    print(x, y, z)

2 2 4
2 3 8
4 3 64
4 2 16
4 4 256
5 3 125
5 2 25
5 4 625
2 4 16
3 4 81
3 3 27
3 2 9


# Three Integer Variable 10 bits Factorial

In [31]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
assert tc.factorial(x) + 1 == y ** 2
while tc.satisfy([x, y]):
    print(x, y)

0 1
4 5
5 11


# Array of 4 Boolean Variables Constraints

In [33]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
xs = tc.array(4)
assert sum(xs) == 1
while tc.satisfy(xs): # note array is passed directly
    print(tc.values(xs))

[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 1, 0, 0]
[1, 0, 0, 0]


# Array of 4 Integers "All Differents"

In [71]:
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
xs = tc.array(4)
tc.apply(xs, single=lambda x: x < 5) # all values < 5
tc.apply(xs, dual=lambda x, y: x != y)
while tc.satisfy(xs): # note array is passed directly
    print(tc.values(xs))

[2, 1, 4, 0]
[3, 1, 0, 4]
[4, 1, 3, 0]
[2, 0, 3, 1]
[1, 2, 3, 0]
[2, 1, 3, 0]
[0, 2, 1, 4]
[2, 1, 0, 3]
[2, 0, 1, 3]
[2, 3, 1, 0]
[0, 2, 1, 3]
[0, 2, 3, 1]
[0, 3, 1, 2]
[4, 2, 1, 3]
[2, 3, 0, 1]
[4, 2, 0, 1]
[0, 1, 3, 2]
[4, 3, 0, 1]
[4, 2, 1, 0]
[4, 3, 1, 0]
[4, 0, 3, 2]
[4, 1, 3, 2]
[4, 0, 2, 3]
[4, 1, 2, 3]
[0, 1, 2, 3]
[0, 4, 3, 2]
[0, 4, 2, 3]
[2, 4, 0, 1]
[2, 4, 1, 0]
[0, 4, 1, 2]
[2, 4, 0, 3]
[0, 4, 2, 1]
[2, 4, 3, 0]
[0, 3, 2, 1]
[2, 4, 3, 1]
[0, 4, 3, 1]
[2, 4, 1, 3]
[0, 4, 1, 3]
[4, 3, 2, 0]
[4, 1, 2, 0]
[4, 3, 0, 2]
[4, 1, 0, 2]
[4, 1, 0, 3]
[4, 2, 0, 3]
[4, 0, 2, 1]
[4, 3, 2, 1]
[4, 2, 3, 0]
[4, 0, 1, 2]
[4, 0, 1, 3]
[4, 2, 3, 1]
[4, 0, 3, 1]
[4, 3, 1, 2]
[0, 2, 4, 3]
[0, 1, 4, 3]
[2, 1, 4, 3]
[2, 0, 4, 3]
[0, 1, 3, 4]
[2, 1, 3, 4]
[2, 0, 3, 4]
[0, 2, 3, 4]
[2, 3, 1, 4]
[0, 3, 1, 4]
[2, 0, 1, 4]
[0, 3, 2, 4]
[0, 1, 2, 4]
[2, 3, 0, 4]
[2, 1, 0, 4]
[2, 3, 4, 0]
[0, 1, 4, 2]
[0, 3, 4, 2]
[1, 0, 4, 2]
[3, 0, 4, 2]
[1, 0, 2, 4]
[0, 3, 4, 1]
[2, 3, 4, 1]
[2, 0, 4, 1]
[0, 2, 4, 1]

# Matrix of 4x4 Boolean Variables Constraints

In [41]:
tc = peqnp.TheCore(bits=4, key='tutorial', folder='db/')
xs = [tc.array(2) for _ in range(2)]
for i in range(2):
    assert sum(xs[i]) == 1
while tc.satisfy(tc.flatten(xs)): # note matrix is flatten to array and passed directly
    print(tc.values(tc.flatten(xs)))
    for i in range(2):
        print(tc.values(xs[i]))

[0, 1, 0, 1]
[0, 1]
[0, 1]
[1, 0, 0, 1]
[1, 0]
[0, 1]
[0, 1, 1, 0]
[0, 1]
[1, 0]
[1, 0, 1, 0]
[1, 0]
[1, 0]


# Matrix Transposition With Numpy

In [43]:
!pip install numpy

In [52]:
import numpy
tc = peqnp.TheCore(bits=10, key='tutorial', folder='db/')
xs = numpy.array([tc.array(4) for _ in range(4)])
for i in range(4):
    assert sum(xs[i]) == 1
    assert sum(xs.T[i]) == 1
while tc.satisfy(tc.flatten(xs)): # note matrix is flatten to array and passed directly
    print(tc.values(tc.flatten(xs)))
    for i in range(4):
        print(tc.values(xs[i]))

[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
[0, 1, 0, 0]
[1, 0, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]
[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]
[0, 1, 0, 0]
[1, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]
[1, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[0, 0, 1, 0]
[0, 1, 0, 0]
[1, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 1]
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 1]
[0, 1, 0, 0]
[1, 0, 0, 0]
[0, 0, 1, 0]
[0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[0, 1, 0, 0]
[0, 0, 1, 0]
[1, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[0, 0, 1, 0]
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]
[0, 0, 1, 0]
[1, 0, 0, 0]
[0, 0, 0, 1]
[0, 1, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[0, 0, 1, 0]
[0, 1, 0, 0]
[0, 0, 0, 1]
[1,

# Matrix Operations With Numpy

In [69]:
import numpy
tc = peqnp.TheCore(bits=4, key='tutorial', folder='db/')
xs = numpy.reshape(numpy.array([tc.array(2) for _ in range(2)]), (2, 2))
ys = numpy.reshape(numpy.array([tc.array(2) for _ in range(2)]), (2, 2))
for i in range(2):
    assert sum(xs[i]) == 1
    assert sum(xs.T[i]) == 1
    for j in range(2):
        assert ys[i][j] <= 1
assert (numpy.multiply(xs, ys) <= 1).all()
while tc.satisfy(tc.flatten(xs) + tc.flatten(ys)): # note matrix is flatten to array and passed directly
    print(numpy.vectorize(int)(xs))
    print(numpy.vectorize(int)(ys))
    print(numpy.multiply(numpy.vectorize(int)(xs), numpy.vectorize(int)(ys))) # check
    print()

[[0 1]
 [1 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]

[[1 0]
 [0 1]]
[[0 1]
 [0 0]]
[[0 0]
 [0 0]]

[[0 1]
 [1 0]]
[[0 0]
 [1 0]]
[[0 0]
 [1 0]]

[[0 1]
 [1 0]]
[[1 0]
 [0 0]]
[[0 0]
 [0 0]]

[[0 1]
 [1 0]]
[[0 1]
 [1 0]]
[[0 1]
 [1 0]]

[[1 0]
 [0 1]]
[[1 0]
 [1 0]]
[[1 0]
 [0 0]]

[[0 1]
 [1 0]]
[[0 0]
 [0 1]]
[[0 0]
 [0 0]]

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 0]
 [0 0]]

[[0 1]
 [1 0]]
[[0 1]
 [0 0]]
[[0 1]
 [0 0]]

[[1 0]
 [0 1]]
[[1 1]
 [0 0]]
[[1 0]
 [0 0]]

[[1 0]
 [0 1]]
[[1 0]
 [0 0]]
[[1 0]
 [0 0]]

[[0 1]
 [1 0]]
[[1 1]
 [1 0]]
[[0 1]
 [1 0]]

[[0 1]
 [1 0]]
[[0 0]
 [1 1]]
[[0 0]
 [1 0]]

[[1 0]
 [0 1]]
[[1 1]
 [1 0]]
[[1 0]
 [0 0]]

[[0 1]
 [1 0]]
[[0 1]
 [0 1]]
[[0 1]
 [0 0]]

[[1 0]
 [0 1]]
[[1 0]
 [1 1]]
[[1 0]
 [0 1]]

[[1 0]
 [0 1]]
[[0 1]
 [1 1]]
[[0 0]
 [0 1]]

[[0 1]
 [1 0]]
[[1 0]
 [1 1]]
[[0 0]
 [1 0]]

[[0 1]
 [1 0]]
[[1 1]
 [0 1]]
[[0 1]
 [0 0]]

[[1 0]
 [0 1]]
[[0 1]
 [0 1]]
[[0 0]
 [0 1]]

[[0 1]
 [1 0]]
[[1 1]
 [0 0]]
[[0 1]
 [0 0]]

[[0 1]
 [1 0]]
[[0 1]
 [1 1]]
[[0 

# Exponential Diophantine Equations

In [82]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
_3 = tc.int(value=3)
assert _3 ** x == y ** 5 + z
assert x > 1
assert y > 1
while tc.satisfy([x, y, z]):
    print(x, y, z)

7 4 1163
5 2 211
7 2 2155
4 2 49
6 3 486
6 2 697
5 3 0
7 3 1944


# Permutations

In [85]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
tc.permutations([1, 2, 3], [x, y, z])
while tc.satisfy([x, y, z]):
    print(x, y, z)

1 2 3
1 3 2
2 1 3
2 3 1
3 1 2
3 2 1


# Subsets

In [92]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
xs = tc.subset(3, [1, 2, 3, 4, 5], 0) # a subset of {1, 2, 3, 4, 5} of at most 3 elements and empty element is 0
while tc.satisfy(xs):
    print(tc.values(xs))

[0, 2, 3, 0, 5]
[1, 0, 0, 4, 5]
[0, 2, 3, 4, 0]
[1, 0, 3, 0, 5]
[1, 2, 0, 4, 0]
[0, 0, 0, 0, 5]
[1, 0, 0, 0, 0]
[1, 0, 0, 0, 5]
[0, 0, 3, 0, 0]
[0, 2, 0, 0, 0]
[0, 2, 3, 0, 0]
[0, 0, 3, 0, 5]
[0, 2, 0, 0, 5]
[0, 0, 3, 4, 5]
[0, 0, 0, 4, 5]
[0, 2, 0, 4, 5]
[1, 2, 0, 0, 5]
[0, 0, 3, 4, 0]
[1, 0, 0, 4, 0]
[0, 2, 0, 4, 0]
[0, 0, 0, 4, 0]
[1, 2, 0, 0, 0]
[1, 0, 3, 0, 0]
[1, 2, 3, 0, 0]
[1, 0, 3, 4, 0]


# Sequencing

In [96]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
xs = tc.array(3)
ys = tc.array(3)
tc.sequencing(xs, ys, [1, 2, 3, 4]) # xs positions, ys elements from array
while tc.satisfy(xs + ys):
    print(tc.values(xs), tc.values(ys))

[0, 0, 0] [1, 1, 1]
[0, 1, 0] [1, 2, 1]
[1, 0, 0] [2, 1, 1]
[3, 3, 1] [4, 4, 2]
[1, 1, 3] [2, 2, 4]
[3, 2, 3] [4, 3, 4]
[1, 3, 2] [2, 4, 3]
[3, 3, 2] [4, 4, 3]
[3, 1, 2] [4, 2, 3]
[1, 2, 2] [2, 3, 3]
[3, 2, 2] [4, 3, 3]
[1, 1, 2] [2, 2, 3]
[3, 1, 1] [4, 2, 2]
[3, 0, 2] [4, 1, 3]
[3, 2, 1] [4, 3, 2]
[1, 2, 1] [2, 3, 2]
[3, 0, 1] [4, 1, 2]
[0, 2, 2] [1, 3, 3]
[3, 3, 0] [4, 4, 1]
[3, 2, 0] [4, 3, 1]
[3, 1, 0] [4, 2, 1]
[3, 0, 0] [4, 1, 1]
[3, 1, 3] [4, 2, 4]
[3, 0, 3] [4, 1, 4]
[0, 0, 2] [1, 1, 3]
[3, 3, 3] [4, 4, 4]
[1, 3, 3] [2, 4, 4]
[0, 1, 2] [1, 2, 3]
[0, 3, 2] [1, 4, 3]
[1, 0, 2] [2, 1, 3]
[0, 3, 0] [1, 4, 1]
[0, 2, 0] [1, 3, 1]
[1, 2, 3] [2, 3, 4]
[0, 2, 1] [1, 3, 2]
[0, 0, 1] [1, 1, 2]
[0, 3, 1] [1, 4, 2]
[0, 3, 3] [1, 4, 4]
[0, 0, 3] [1, 1, 4]
[1, 2, 0] [2, 3, 1]
[0, 1, 1] [1, 2, 2]
[2, 3, 2] [3, 4, 3]
[2, 0, 2] [3, 1, 3]
[2, 2, 2] [3, 3, 3]
[2, 2, 1] [3, 3, 2]
[2, 0, 1] [3, 1, 2]
[2, 3, 1] [3, 4, 2]
[2, 1, 1] [3, 2, 2]
[2, 1, 2] [3, 2, 3]
[1, 1, 1] [2, 2, 2]
[1, 3, 1] [2, 4, 2]


# IFF

In [100]:
tc = peqnp.TheCore(bits=4, key='tutorial', folder='db/')
x = tc.int()
bit = tc.int(size=1)
assert x.iff(bit[0], tc.zero) == tc.zero.iff(-bit[0], x) 
while tc.satisfy([x, bit]):
    print(bit.binary, x)

[True] 0
[True] 1
[True] 4
[True] 5
[True] 8
[True] 2
[True] 3
[True] 6
[True] 7
[True] 12
[True] 10
[True] 9
[True] 13
[True] 14
[True] 11


In [120]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
x = tc.int()
y = tc.int()
z = tc.int()
bit = tc.int(size=1)
assert (x ** 3 + y ** 3 - z ** 3).iff(bit[0], x ** 3 - y ** 3 - z ** 3) == 10
while tc.satisfy([x, y, z, bit]):
    if not bit.binary[0]:
        print(x ** 3 + y ** 3 - z ** 3)
    else:
        print(x ** 3 - y ** 3 - z ** 3)

10


In [123]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
data = [2, 3, 5, 7, 11]
bit = tc.int(size=5)
assert sum(tc.zero.iff(bit[i], data[i]) for i in range(5)) == 12
while tc.satisfy([bit]):
    print(bit.binary)

[True, True, False, True, False]
[False, False, True, True, False]


In [124]:
tc = peqnp.TheCore(bits=16, key='tutorial', folder='db/')
data = [2, 3, 5, 7, 11]
xs = tc.subset(5, data, tc.zero)
assert sum(xs) == 12
while tc.satisfy(xs):
    print(tc.values(xs))

[0, 0, 5, 7, 0]
[2, 3, 0, 7, 0]


# Work in progress... https://twitter.com/maxtuno